export const hashtags = [
  { hashtag: 'competition' },
  { hashtag: 'influencer' },
  { hashtag: 'influencermarketing' },
  { hashtag: 'fridayfeeling' },
  { hashtag: 'MondayMotivation' },
  { hashtag: 'tbt' },
  { hashtag: 'traveltuesday' },
  { hashtag: 'vegan' },
  { hashtag: 'fitness' },
  { hashtag: 'COVID19' },
  { hashtag: 'pharmtech' },
  { hashtag: 'art' },
  { hashtag: 'MarchMadness' },
  { hashtag: 'love' },
];
